---
title: Dostępność w polskim prawie
description: Schemat ilustrujący hierarchię aktów prawnych dotyczących dostępności.
tags: [dostępność, prawo, akty prawne, hierarchia]
theme: default
---

graph TD
    %% Poziom 1: Konstytucja RP
    konstytucja[🇵🇱 Konstytucja RP]
    click konstytucja "" "Konstytucja Rzeczypospolitej Polskiej z dnia 2 kwietnia 1997 r. (Dz.U. z 1997 r. Nr 78, poz. 483)"
    konstytucja --> uzd
    konstytucja --> rtv
    konstytucja --> p_budowlane
    konstytucja --> k_cywilny
    konstytucja --> k_wyborczy
    konstytucja --> k_morski
    

    %% Poziom 2: Umowy Międzynarodowe / Prawo UE
    kpon[🇺🇳 Konwencja ONZ o Prawach Osób Niepełnosprawnych]
    click kpon "" "Konwencja o prawach osób niepełnosprawnych, sporządzona w Nowym Jorku dnia 13 grudnia 2006 r. (Dz.U. z 2012 r. poz. 1169)"]
    kpon --> uzd
    eaa[🇪🇺 Dyrektywa Parlamentu Europejskiego i Rady w sprawie wymogów dostępności produktów i usług]
    click eaa "" "Dyrektywa Parlamentu Europejskiego i Rady (UE) 2019/882 z dnia 17 kwietnia 2019 r. w sprawie wymogów dostępności produktów i usług"
    eaa --transpozycja--> pad
    eaa --"norma techniczna"--> en301549
    ead[🇪🇺 Dyrektywa  w sprawie dostępności stron internetowych i aplikacji mobilnych podmiotów publicznych]
    click ead "" "Dyrektywa Parlamentu Europejskiego i Rady (UE) 2016/2102 z dnia 26 października 2016 r. w sprawie dostępności stron internetowych i mobilnych aplikacji organów sektora publicznego"
    ead --transpozycja--> udc
    ead --"norma techniczna"--> en301549
    ue_loty[🇪🇺 Rozporządzenie w sprawie praw osób niepełnosprawnych oraz osób o ograniczonej sprawności ruchowej w podróżach lotniczych]
    click ue_loty "" "Rozporządzenie (WE) nr 1107/2006 z dnia 5 lipca 2006 r. w sprawie praw osób niepełnosprawnych oraz osób o ograniczonej sprawności ruchowej w podróżach lotniczych
    ue_loty --transpozycja--> p_lotnicze
    ue_autobusy[🇪🇺 Rozporządzenie UE w sprawie autobusów]
    click ue_autobusy "" "Rozporządzenie Parlamentu Europejskiego i Rady (UE) nr 181/2011 z dnia 16 lutego 2011 r. dotyczące praw pasażerów w transporcie autobusowym i autokarowym"
    karta[🇪🇺 Karta praw podstawowych]
    click karta "" "Karta Praw Podstawowych Unii Europejskiej (Dz. Urz. UE C 303 z 14.12.2007 r.)"
    karta --> uzd
    %% Poziom 3: Ustawy
    subgraph
    title "Ustawy"
k_cywilny[Kodek cywilny]
click k_cywilny "" "Ustawa z dnia 23 kwietnia 1964 r. – Kodeks cywilny (Dz.U. z 1964 r. Nr 16, poz. 93)"
k_morski[Kodeks morski]
click k_morski "" "Ustawa z dnia 18 września 2001 r. – Kodeks morski (Dz.U. z 2001 r. Nr 138, poz. 1545)"
    k_wyborczy[Kodeks wyborczy]
    click k_wyborczy "" "Ustawa z dnia 5 stycznia 2011 r. – Kodeks wyborczy"
    pzp[Prawo zamówień publicznych]
    click pzp "" "Ustawa z dnia 11 września 2019 r. – Prawo zamówień publicznych"
    p_lotnicze[Prawo lotnicze]
    click p_lotnicze "" "Ustawa z dnia 3 lipca 2002 r. – Prawo lotnicze"
    p_budowlane[Prawo budowlane]
    click p_budowlane "" "Ustawa z dnia 7 lipca 1994 r. – Prawo budowlane"
    p_telekomunikacyjne[Prawo telekomunikacyjne]
click p_telekomunikacyjne "" "Ustawa z dnia 16 lipca 2004 r. – Prawo telekomunikacyjne"

    uzd[Ustawa o zapewnianiu dostępności osobom ze szczególnymi potrzebami]
    click uzd "" "Ustawa z dnia 19 lipca 2019 r. o zapewnianiu dostępności osobom ze szczególnymi potrzebami (Dz.U. z 2019 r. poz. 1696)"
    udc[Ustawa o dostępności cyfrowej]
    click udc "" "Ustawa z dnia 4 kwietnia 2019 r. o dostępności cyfrowej stron internetowych i aplikacji mobilnych podmiotów publicznych (Dz.U. z 2019 r. poz. 848)
    udc --"norma techniczna"--> en301549
    pad[Ustawa o dostępności niektórych produktów i usług]
click pad "" "Ustawa z dnia 26 kwietnia 2024 r. o zapewnianiu spełniania wymagań dostępności niektórych produktów i usług przez podmioty gospodarcze (Dz.U. z 2024 r. poz. 1171)
    pad --odwołanie-->kredyt
    pad --odwołanie--> hipoteczny
    pad --odwołanie--> instrumenty
    pad --odwołanie--> uup
    pad --odwołanie--> usude
    pad --"norma techniczna"--> en301549
    pad --delegacja--> wytyczne_pfron
    rtv[Ustawa o radiofonii i telewizji]
    click rtv "" "Ustawa z dnia 29 grudnia 1992 r. o radiofonii i telewizji (Dz.U. z 1993 r. Nr 7, poz. 34)"
    rtv --> krrit_ad
    rtv --> krrit_cc
    rtv --> krrit_pjm
    pjm[Ustawa o języku migowym]
    click pjm "" "Ustawa z dnia 19 sierpnia 2011 r. o języku migowym i innych środkach komunikowania się (Dz.U. z 2011 r. Nr 209, poz. 1243)"
    upk[Ustawa o prawach konsumenta]
    click upk "" "Ustawa z dnia 30 maja 2014 r. o prawach konsumenta     (Dz.U. z 2014 r. poz. 827)"
    usude[Ustawa o świadczeniu usług drogą elektroniczną]
    click usude "" "Ustawa z dnia 18 lipca 2002 r. o świadczeniu usług drogą elektroniczną (Dz.U. z 2002 r. Nr 144, poz. 1204)"
    zbiorkom[Ustawa o publicznym transporcie zbiorowym]
    click zbiorkom "" "Ustawa z dnia 16 grudnia 2010 r. o publicznym transporcie zbiorowym (Dz.U. z 2011 r. Nr 5, poz. 13)"
    kredyt[Ustawa o kredycie konsumenckim]
    click kredyt "" "Ustawa z dnia 12 maja 2011 r. o kredycie konsumenckim (Dz.U. z 2011 r. Nr 126, poz. 715)"
    hipoteczny[Ustawa o kredycie hipotecznym]
    click hipoteczny ""  "Ustawa z dnia 23 marca 2017 r. o kredycie hipotecznym oraz o nadzorze nad pośrednikami kredytu hipotecznego i agentami (Dz.U. z 2017 r. poz. 819)"
    instrumenty[Ustawa o obrocie instrumentami finansowymi]
    uup[Ustawa o usługach płatniczych]
    click uup "" "Ustawa z dnia 19 sierpnia 2011 r. o usługach płatniczych (Dz.U. z 2011 r. Nr 199, poz. 1175)"
end


    %% Poziom 4: Rozporządzenia i akty wykonawcze
    subgraph
    title "Rozporządzenia"
    w_budynki[Warunki dla budynków]
    click w_budynki "" "Rozporządzenie Ministra Infrastruktury z dnia 12 kwietnia 2002 r. w sprawie warunków technicznych, jakim powinny odpowiadać budynki i ich usytuowanie"
    w_metro[Wytyczne dla metra]
    click w_metro "" "29. Rozporządzenie Ministra Infrastruktury z dnia 16 maja 2023 r. w sprawie warunków technicznych, jakim powinny odpowiadać obiekty budowlane metra i ich usytuowanie – określa wymagania dotyczące dostępności stacji metra dla osób z niepełnosprawnościami
"w_telekomunikacja[Dostępność usług telekomunikacyjnych]
click w_telekomunikacja "" "Rozporządzenie Ministra Administracji i Cyfryzacji z dnia 26 marca 2014 r. w sprawie szczegółowych wymagań dotyczących świadczenia udogodnień dla osób niepełnosprawnych przez dostawców publicznie dostępnych usług telefonicznych"
w_wybory[Dostępność lokali wyborczych]
click w_wybory "" "Rozporządzenie Ministra Infrastruktury z dnia 29 lipca 2011 r. w sprawie lokali obwodowych komisji wyborczych dostosowanych do potrzeb wyborców niepełnosprawnych  
"end
    %% Poziom 5: Akty prawa miejscowego

    
    %% Poziom 6: Normy i standardy
    subgraph
    title "Normy i zalecenia"
    en301549[EN 301 549 V3.2.1<br>Accessibility requirements for ICT products and services]
    wytyczne_mfipr[Wytyczne dotyczące realizacji zasad równościowych w ramach funduszy unijnych na lata 2021-2027]
    wytyczne_pfron[Wytyczne Jak zapewnić dostępność produktów i usług]
    krrit_ad[Rekomendacje KRRiT dotyczące audiodeskrypcji]
    krrit_cc[Rekomendacje KRRiT dotyczące napisów dla niesłyszących]
    krrit_pjm[Stanowisko KRRiT w sprawie tłumaczenia na polski język migowy]


